services:
  - type: web
    name: mindscape
    env: python
    region: oregon  # Choose the region closest to your users
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_APP
        value: wsgi.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true
    healthCheckPath: /health
    disk:
      name: mindscape-data
      mountPath: /data
      sizeGB: 1
